export const statusCodes = {
  'Status code 400': 'Bad Request',
  'Status code 401': 'Unauthorized',
  'Status code 402': 'Payment Required',
  'Status code 403': 'Forbidden',
  'Status code 404': 'Not Found',
  'Status code 405': 'Method Not Allowed',
  'Status code 406': 'Not Acceptable',
  'Status code 407': 'Proxy Authentication Required',
  'Status code 408': 'Request Timeout',
  'Status code 409': 'Conflict',
  'Status code 410': 'Gone',
  'Status code 411': 'Length Required',
  'Status code 412': 'Precondition Failed',
  'Status code 413': 'Payload Too Large',
  'Status code 414': 'URI Too Long',
  'Status code 415': 'Unsupported Media Type',
  'Status code 416': 'Range Not Satisfiable',
  'Status code 417': 'Expectation Failed',
  'Status code 418': "I'm a teapot",
  'Status code 500': 'Internal Server Error',
  'Status code 501': 'Not Implemented',
  'Status code 502': 'Bad Gateway',
  'Status code 503': 'Service Unavailable',
  'Status code 504': 'Gateway Timeout',
  'Status code 505': 'HTTP Version Not Supported',
  'Status code 506': 'Variant Also Negotiates',
  'Status code 507': 'Insufficient Storage',
  'Status code 508': 'Loop Detected',
  'Status code 510': 'Not Extended',
  'Status code 511': 'Network Authentication Required',
};
